# Generated by Django 3.0.5 on 2020-05-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procuct',
            new_name='Product',
        ),
    ]
