# Generated by Django 3.0.5 on 2020-05-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procuct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=300)),
                ('desc2', models.CharField(default='', max_length=3000)),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
