# Generated by Django 3.0.5 on 2020-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='features',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='productlist',
            name='use',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
