# Generated by Django 3.0.6 on 2020-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=300)),
            ],
        ),
    ]
