# Generated by Django 3.0.6 on 2020-05-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
