# Generated by Django 3.0.6 on 2020-05-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
