# Generated by Django 3.0.5 on 2020-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Username',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='Email',
            field=models.CharField(max_length=80),
        ),
    ]
